# Generated by Django 6.0.2 on 2026-03-03 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waitlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlistentry",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="waitlistentry",
            name="last_name",
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="waitlistentry",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
