name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source ~/virtualenv/everyspoon/3.12/bin/activate
            cd ~/everyspoon
            git pull origin main
            pip install -r requirements.py
            python manage.py migrate --noinput
            touch tmp/restart.txt